name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
    
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
       heroku_app_name: "bmi-em"
       heroku_email: "emedu442@gmail.com"
       
       
         
